const Types = {
    CHANGE_USER : "CHANGE_USER",
    LOGOUT : "LOGOUT",

    ADD_PRODUCT:"ADD_PRODUCT",
    REMOVE_PRODUCT:"REMOVE_PRODUCT",
    CLEAN_CART:"CLEAN_CART",
    UPDATE_CART:"UPDATE_CART",
    
    //
    ADD_ADDRESS_CART: "ADD_ADDRESS_CART",
    UPDATE_ADDRESS_CART: "ADD_ADDRESS_CART",



}

export default Types