version: '3.3'
services:
  backend:
    build:
      context: ./back-end 
    ports:
      - ${PORT_BACK}:${PORT_BACK}
    volumes:
      - ./back-end:/usr/app
    env_file:
      - ./.env
  frontend:
    build:
      context: ./front-end 
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./front-end:/usr/app
    env_file:
      - ./.env  
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password

    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_config:/etc/mysql 
volumes:
  mysql_data:
  mysql_config: